---
name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      -
        name: Get version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      -
        name: Check if current commit is tagged
        id: check_tag
        run: |
          TAG=$(git describe --tags --exact-match ${{ github.sha }} 2>/dev/null || echo "")
          if [ -n "$TAG" ]; then
            echo "IS_TAGGED=true" >> $GITHUB_ENV
          else
            echo "IS_TAGGED=false" >> $GITHUB_ENV
          fi
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ github.repository }}:${{ env.VERSION }}' || '' }}
          labels: |
            org.opencontainers.image.title=Hugging Face CLI Cache Manager
            org.opencontainers.image.description=A web application for managing the Hugging Face cache, providing a user interface for viewing cache statistics, browsing cached files, downloading models, and clearing the cache.
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
      -
        name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = process.env.GITHUB_REF.replace('refs/tags/', '');
            const version = tag.replace('v', '');
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: `Release ${version}`,
              body: `Release of version ${version}\n\nSee the [CHANGELOG](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CHANGELOG.md) for details.`,
              draft: false,
              prerelease: false
            });
            console.log(`Created release: ${release.html_url}`);